version: "3"
services:
  selenium-hub:
    image: selenium/hub
    container_name: selenium-hub
    ports:
      - "4444:4444"

  chrome:
    image: selenium/node-chrome
    depends_on:
      - selenium-hub
    environment:
      - HUB_PORT_4444_TCP_ADDR=selenium-hub
      - HUB_PORT_4444_TCP_PORT=4444
      - NODE_MAX_INSTANCES=5
      - NODE_MAX_SESSION=5

  search-module:
    image: franautomation/containertest:1.0
    container_name: search-module
    depends_on:
      - chrome
    environment:
      - MODULE=TestNGXML.xml
      - BROWSER=chrome
      - SELENIUM_HUB=selenium-hub
    volumes:
      - ./search-module-result:/test-output
      - ./outputFolder:/usr/share/tag/outputfolder


